### ISSUE TITLE
Review Module 1 - Open is a Noun a Verb an Attitude!

### ISSUE THREAD

**Issue by emmairwin** [mozilla/open-innovation-curriculum#20]
Please review module information, learning outcomes and proposed resources and complete feedback checklist (listed at bottom).

## Module - Open is a Noun a Verb an Attitude!
* ([title credit Clint Lalonde blog post](http://clintlalonde.net/2012/10/18/open-is-a-noun-verb-adjective-and-an-attitude/))

This module helps learners understand the ecosystem and attributes  of ‘open’, why it matters, and what it isn’t by providing an overview of open source, and why contribution can be a valuable career move that also helps save the world.

## LEARNING OUTCOMES:
Links are content suggestions, whole or in part

* What we mean by open and why does it matter
* * [Introduction to Working Open](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/introduction-to-working-open/) (Open Leadership)
  *  [Understanding the Open in Open Source](http://foss2serve.org/index.php/Understanding_the_Open_in_OpenSource_Activity) (TOS)
  * [Introduction to FOSS & HFOSS](http://foss2serve.org/index.php/Intro_to_FOSS_(Activity))  (TOS)
* Open in the Wild - Who is using it, how it changed history, what it’s not : open washing etc.
  * [Open is an Attitude](https://docs.google.com/presentation/d/1uCI2lEvb0aYfCZ3amkH5ASuXiKOjGjYSXBNw2HM5Nho/edit#slide=id.p)  (Emma/Mozilla - story of Firefox 1.0)
* How FOSS contribution can accelerate technical careers / Employability
  * [HFOSS employment](http://www.openhealthnews.com/story/2017-03-26/open-source-job-opportunities-grow-humanitarian-crisis-relief-groups) (article)

## ASSESSMENT (one of):

* (action) [Interview someone involved in Open Source](http://wiki.openhatch.org/Open_Source_Comes_to_Campus/Curriculum/Career_Panel) using Open Hatch’s panel questions, share this with your club.
* (action)  [hold a mock debate](http://teachingopensource.org/learning-material/open-vs-proprietary-mock-debate/) (open or proprietary - from TOS) 
* (self assessment)  quiz on learning outcomes in Teachable.
* ?

## Review Checklist:
Open on a meta level to links, resources that already exist on this topic broadly, or specific to modules!  Thanks.

- [ ] Review title & description - provide feedback, if any.
- [ ] Review learning outcomes - do these seem right? What would you change/add/remove?
- [ ] Review proposed content (under each learning outcome).  What additional resources would you suggest we consider? 
- [ ] Review assessment list - provide feedback, suggestions for other criteria. 
- [ ] Leave comments in this issue or email Emma eirwin at mozilla.com 

## Related Issues
Meta #19

**Comment by Mte90** [comment]
About that topic I written in the past 2 articles about my personal experience:

- https://mte90.net/2016/01/why-i-do-with-open/
- https://mte90.net/2017/01/i-do-open-2017-edition/

**Comment by jgmac1106** [comment]
I can help work on the objectives. In the future I would hold off on writing assessment strategies until you decide on what exactly you want to measure. 

Understanding the Open and open source has decent objectives: http://foss2serve.org/index.php/Understanding_the_Open_in_OpenSource_Activity though they are rather low level and not too production based but that makes sense for an intro module that should not be too time consuming.

As a useful resource you may want to look at the [Depth of Knowledge chart](http://www.niesc.k12.in.us/index.cfm/staff-development/public-consulting-group-co-teaching-session/depthofknowledgechart-pdf/).

**Comment by jgmac1106** [comment]
* Identify common elements of open source projects.
* Describe how elements of open source are reflected in projects that inspires you.
* Create a shareable summary of an open source project you want to develop.

## Assessments
Objective One could be a quiz or the objective could be combined with second objective.
Objective Two could be an open item response or a blog post.
Objective Three could be something to share on social media or within networks.

While I get folks want to embrace "objectivity" and the efficacy of multiple choice but I encourage you to make the assessments as production based as possible. Let your teaching tools be the best recruiter out there.

**Comment by emmairwin** [comment]
@jgmac1106 super, super helpful, will share a draft here to see if it reflects properly what you have proposed.

**Comment by emmairwin** [comment]
Have updated doc with feedback here, closing issue for now.  Thank you !

https://docs.google.com/document/d/18wnqY_-1vqq7PfzLJvAAIudFVo6PbhZhXxB9pEpQsOs/edit#

**Comment by emmairwin** [comment]
Module 1,  Section 1 : What do we meany by Open ? 

https://emmairwin.github.io/learning-open-source/articles/open-is-an-attitude/what-is-open/

Module 1, Section 2 - History of Open Source 
https://emmairwin.github.io/learning-open-source/articles/open-is-an-attitude/history-of-open/

Module 1, Section 3  
https://emmairwin.github.io/learning-open-source/articles/open-is-an-attitude/opening-your-future/
