### ISSUE TITLE
Review Module 2 - Through the Looking Glass - Evaluating Open Source Projects

### ISSUE THREAD

**Issue by emmairwin** [mozilla/open-innovation-curriculum#21]
Please review module information, learning outcomes and proposed resources and complete feedback checklist (listed at bottom).

## Module - Through the Looking Glass - Evaluating Open Source Projects

Stepping into an open source community can be overwhelming, This module will help people evaluate a community framework, behaviors and factors of community health that can help in the evaluation and 

### LEARNING OUTCOMES:
(Links are content suggestions, whole or in part)

* How to find and evaluate an open project for contribution
  * What do you want to do?  (technical and non technical ways to test the water
  * [How to contribute to Open Source some reading](https://opensource.guide/how-to-contribute/) (Github)
  * [How to contribute checklist](https://opensource.guide/how-to-contribute/) (but we would build on it because I see a few things missing around CoC, D&I)
* Understanding Licences & Legal Things in FOSS
  * Open Source License
  * Creative Commons Licences
  * [Contributor License Agreements](https://twitter.com/sunnydeveloper/status/892444391725453312) (what/why/when)
* Codes of Conduct & Community Health
 * [Frameworks for Governance, Incentive & Consequence](https://medium.com/mozilla-open-innovation/frameworks-for-governance-incentive-and-consequence-in-foss-e1de6c091bdc)
 * [Women in Open Source talk](http://webchick.net/files/presentations/women-in-open-source-owv09-2009-06.pdf) (getting involved portion)(Angie Byron)

### ASSESSMENT (one of):

* (self assessment)  quiz on learning outcomes in Teachable.
* Treasure hunt - evaluate 3 open source communities to find these things ie. (license, maintainers,  if they have a CLA, 1 technical and one non-technical task) 
?

## Review Checklist
Open on a meta level to links, resources that already exist on this topic broadly, or specific to modules!  Thanks.

- [ ] Review title & description - provide feedback, if any.
- [ ] Review learning outcomes - do these seem right? What would you change/add/remove?
- [ ] Review proposed content (under each learning outcome).  What additional resources would you suggest we consider? 
- [ ] Review assessment list - provide feedback, suggestions for other criteria. 
- [ ] Leave comments in this issue or email Emma eirwin at mozilla.com 

## Related Issues
[Reference meta issues and past issues] #

**Comment by Mte90** [comment]
I think that also is important to ask Why do you like this project?
Because the motivation of a person are very important for the evaluation, only what you want to do is not enough.
In my personal document https://docs.google.com/document/d/1kg7CxZIyebsXEjXWxGKxov84NWgEm-eQ8FFFWC2AsJk/edit I explain that :-)

**Comment by jgmac1106** [comment]
I agree with @mte90, In fact I might take the objective I wrote for module one and move it here.

There is a lot of content in these modules. Focus on just the first and last one (to get at D&I early)
Make the others their own module. Maybe D&I gets its own module.

I would suggest renaming this module around into "Celebrating Open Source Projects"
## Objectives
- Evaluate an open source community.
- Describe opportunities available to a variety of personas.

## Learning Tools
I would make a graphic organizer of the elements and share it.
## Assessments
The treasure hunt is interesting. I may make more scripted. As this could be autoscored. So take well known open source projects and make treasure maps.
Develop an open source project trading card. Take the personas from the GitHub resource, find the real lief equivalent person (or make a fictional) and make a trading card.
Write a post describing why someone should join a specific open source project. Try in under a 150 words or a >1 minute video to describe how the project is governed.

**Comment by emmairwin** [comment]
Module 2

section 1 - Evaluating Open Projects
https://emmairwin.github.io/learning-open-source/articles/stepping-into-opensource/evaluating-open-projects/

section 2 - Licensing
https://emmairwin.github.io/learning-open-source/articles/stepping-into-opensource/licensing/

section 3 - community health 
https://emmairwin.github.io/learning-open-source/articles/stepping-into-opensource/community-health/
