### ISSUE TITLE
Review Module 3 - Opening Your Project 101

### ISSUE THREAD

**Issue by emmairwin** [mozilla/open-innovation-curriculum#22]
Please review module information, learning outcomes and proposed resources and complete feedback checklist (listed at bottom).

##  Module -  Opening Your Project 101
So you want to open source your project?  This module will take learners through the first steps using Design Thinking to identify and design for potential contributors with a lens for diversity, and empowered successful contribution pathways.

### LEARNING OUTCOMES:

* How to ‘Open’ the door for a new FOSS project.
  * [Starting an Open Source project](https://opensource.guide/starting-a-project/) (Github)
  * [Opening your Project](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/) (open leadership training)
  * Code of Conduct
* The basics of designing for participation in your project
  * [What is participation design anyway](http://tiptoes.ca/by-htm/)?
  * [Diversity & Inclusion Best Practices](https://medium.com/mozilla-open-innovation) (select best practices from our series)
  * [Writing good Open Tasks](http://tiptoes.ca/how-to-write-a-good-open-task/)
  * [How to find your first Open Source bug](https://medium.freecodecamp.org/finding-your-first-open-source-project-or-bug-to-work-on-1712f651e5ba) (Freecode Camp)
  * [How to find your Open Source Goldilocks Zone](https://medium.freecodecamp.org/searching-for-your-goldilocks-issue-f23b3a718de) (Freecode Camp)

### ASSESSMENT (one of):

* (self assessment)  quiz on learning outcomes in Teachable.
* [Contributor Personas & Pathways](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/bring-on-contributors-using-personas-and-pathways/) (Open Leadership) 
?

## Review Checklist:
Open on a meta level to links, resources that already exist on this topic broadly, or specific to modules!  Thanks.

- [ ] Review title & description - provide feedback, if any.
- [ ] Review learning outcomes - do these seem right? What would you change/add/remove?
- [ ] Review proposed content (under each learning outcome).  What additional resources would you suggest we consider? 
- [ ] Review assessment list - provide feedback, suggestions for other criteria. 
- [ ] Leave comments in this issue or email Emma eirwin at mozilla.com 

## Related Issues
Meta #19

**Comment by Mte90** [comment]
I think that also think the license is very important.
This repo as an example as no license file and a repo on github without a license is proprietary because is not explained what are the rules for using it/contributing etc.

- https://github.com/blog/1530-choosing-an-open-source-license
- https://help.github.com/articles/licensing-a-repository/

**Comment by jgmac1106** [comment]
You need a link to design thinking in the description.

## Learning Objectives
- Develop user personas and their pathways to contributing to your open source project.
- Write your README.md file sharing your CoC and an explicit plan to address D&I.

I would also recommend splitting this into recruiting and then a second one on establishing governance (the second objective).

The personas and pathways is a perfect assessment.
