### ISSUE TITLE
Review Module 4 - Stepping Into an Open Project (Soft Skills)

### ISSUE THREAD

**Issue by emmairwin** [mozilla/open-innovation-curriculum#23]
Please review module information, learning outcomes and proposed resources and complete feedback checklist (listed at bottom).

##  Module - Stepping Into an Open Project (Soft Skills)

Once you’ve selected a project to contribute to, how should you begin? In this module learners set personal goals for success in ‘steps’ with collaboration as a central theme.

### LEARNING OUTCOMES:
 
* Contribute all the things!  Why code isn’t everything, and it needn’t be where you start.
  * How to ask for help, give help and make collaboration your way of working
  * Communication channel etiquette
  * Mentored bugs
* Setting and reaching goals for contribution.
Like contribution personas pathways exercise but for personal goals. 

### ASSESSMENT (one of):
* Build your contributor pathway ( reverse version of the persona/pathways)
* Quiz on Teachable (or other learning platform)
* ?

## Review Checklist:
Open on a meta level to links, resources that already exist on this topic broadly, or specific to modules!  Thanks.

- [ ] Review title & description - provide feedback, if any.
- [ ] Review learning outcomes - do these seem right? What would you change/add/remove?
- [ ] Review proposed content (under each learning outcome).  What additional resources would you suggest we consider? 
- [ ] Review assessment list - provide feedback, suggestions for other criteria. 
- [ ] Leave comments in this issue or email Emma eirwin at mozilla.com 

## Related Issues
Meta #19

**Comment by Mte90** [comment]
I think that Join is more atractive as term instead of stepping. Usually in every open source project is used Join to "join" the community. It is like a keyword about this step.

**Comment by jgmac1106** [comment]
Can we not say "soft skills?"

Also feels strange that making your project open comes before joining an open project. I would flip flop the order. IRL you always join an open source project before starting your own.

**Comment by jgmac1106** [comment]
## Learning Goals
- Describe how you can contribute to a project to increase collaboration.
## Assessments
Maybe change the assessment to an action plan. Have people set their collaboration goals, the steps to achieve those goals and a target due date.
- Create a shout out and share it describe someone who contributes more to community than code.
