### ISSUE TITLE
Review Module 5 - Stepping into a project (Technical Skills)

### ISSUE THREAD

**Issue by emmairwin** [mozilla/open-innovation-curriculum#24]
Please review module information, learning outcomes and proposed resources and complete feedback checklist (listed at bottom).

* _Links are content suggestions, whole or in part_

## Module - Stepping into a project (Technical Skills)
This module will provide some key technical challenges for basic participation in open source contributing to a Github repository issue queue, codebase and wiki.

### LEARNING OUTCOMES:

* Using the command line (Mac, Windows, Linux)
  *  Terminal, creating making saving, permissions, ssh 
* Github (cloning, forking, committing, pushing etc)
  * Try Github.io  , Github UI
  * 2 step authentication
* Common Communication Tools 
  * IRC, Slack-like alts, Telegram, Mailing lists

### ASSESSMENT (one of):
* Quiz in Teachable
* First Pull request in a cohort Repo (introduce yourself,maybe use thimble project code etc)

## Review Checklist:
Open on a meta level to links, resources that already exist on this topic broadly, or specific to modules!  Thanks.

- [ ] Review title & description - provide feedback, if any.
- [ ] Review learning outcomes - do these seem right? What would you change/add/remove?
- [ ] Review proposed content (under each learning outcome).  What additional resources would you suggest we consider? 
- [ ] Review assessment list - provide feedback, suggestions for other criteria. 
- [ ] Leave comments in this issue or email Emma eirwin at mozilla.com 

## Related Issues
Meta #19

**Comment by jgmac1106** [comment]
Again I would see this as one module with three lessons. I would separate the three objectives into their own lessons each with objectives and assessment. The module could end with an overall performance task...The PR or choosing a First Bug, etc.

**Comment by emmairwin** [comment]
Technical Basics
https://emmairwin.github.io/learning-open-source/articles/technically-open/basics/

Git & Github

https://emmairwin.github.io/learning-open-source/articles/technically-open/github/
