### ISSUE TITLE
Add styling for "Print this Page" link

### ISSUE THREAD

**Issue by flukeout** [mozilla/open-innovation-curriculum#3]
@emmairwin I suggest not bothering with this, the template already comes with a print style sheet and hitting and the page can be printed via normal browser features. Thoughts?

**Comment by emmairwin** [comment]
Hmmmm
Originally I was trying to solve for a use-case: 'download this workshop'.  But you can only download the entire repo.  Maybe that's OK, we're promoting it as a bundle anyway. So
1) Download the entire bundle (main page)  http://mozilla.github.io/participation-curriculum/#personal-leadership
2)  Individual pages, have no print/download link but people can figure it out.
