### ISSUE TITLE
Explore ways o make content available as PDF

### ISSUE THREAD

**Issue by flukeout** [mozilla/open-innovation-curriculum#6]
From discussions with @emmairwin it seems that the content in the templates needs to be available in PDF format...

**Q:** Is that because it makes it easier to print? Or because we want the resources to be available offline? Or both? Let me know!

**What I'll do in the meantime**
- Look into improving the current stylesheets, see how much control we have over the output
- Look into a way to generate downloadable PDFs for each guide

**Problems with printing identified so far**
- Printed resources don't look polished and well designed
- Content and sections can be split awkwardly between pages

**Comment by emmairwin** [comment]
@flukeout Thanks for this! Feeling grateful to have your support in bringing our use cases into the design,

I would say the primary goal of PDF is so we have **resources printed offline, and 'in hand'** .  And that those resources look professional in both online and web versions.  As I was writing up [these](http://mozilla.github.io/participation-curriculum/rapid-prototyping/index.html#2-adaptability-vs-efficiency) workshops I was mindful of what a template might look like.

True point about 'printing' won't always look professional (depends on printer), but that we can have quality versions seems good. I'll ask @geroter to weigh in on that.

As for awkward page breaks hmmmmm .  I wonder  if there is a way to say  '[page break ](http://stackoverflow.com/questions/22601053/pagebreak-in-markdown-while-creating-pdf) using markdown or html' .

What's crazy about this is actually, I feel like I was solving for these issues 15 years ago with CMS.  Some problems we're just always solving I guess!

Thanks again for all  your help!

**Comment by emmairwin** [comment]
Aside, in other research I'm doing on collaborative OER development, and seems to include a lot of things we've talked about for CMS/DB

This site:  http://www.curriki.org/oer/Project-Design-Worksheet-59891/
OER example http://www.curriki.org/oer/Project-Design-Worksheet-59891/
