### ISSUE TITLE
Menu & Framework for Display Not working

### ISSUE THREAD

**Issue by emmairwin** [mozilla/open-innovation-curriculum#7]
http://education.mozilla-community.org/  

shows blank screen

previous links not working either

http://education.mozilla-community.org/#rapid-prototyping

@flukeout - is there a known issue , update to gh pages or something I can do to get these working?

**Comment by flukeout** [comment]
Yikes! That's right - we were hit with the same issue on Clubs Guides.
The code that was used to convert markdown to HTML is no longer hosted by Google where it used to be. I'll create a PR to get this fixed right now.

**Comment by emmairwin** [comment]
Thanks so much @flukeout !!
I also enabled the githug pages theme generator, and need to disable that now you have a fix.
either way thank you for quick response !

**Comment by flukeout** [comment]
No probs! It was my fault setting up the templates in a way that made them reliant on an external resource. Lesson learned.
